[project]
name = "coder-madelainecolicheo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.3",
]

[dependency-groups]
dev = [
    "djlint>=1.36.3",
    "ipython>=8.31.0",
]
